[tool.black]
line-length = 88
skip-string-normalization = 1

[tool.isort]
profile = "black"
line_length = 88

[tool.pyright]
reportOptionalMemberAccess = true
typeCheckingMode = "basic"
ignore = [
    "**/*.ipynb",
    "**/__pycache__",
    ]

[tool.mypy]
warn_return_any = true
